version: '3'

services:

  mongo:
    image: mongo
    container_name: local-mongodb
    environment:
      MONGO_INITDB_DATABASE: quest-user-management
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017